service: isBeerColdService

provider:
  name: aws
  runtime: go1.x
  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
       - dynamodb:Query
       - dynamodb:Scan
       - dynamodb:GetItem
      Resource: "arn:aws:dynamodb:eu-west-1:772563927293:table/IsBeerCold"

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  beerService:
    handler: bin/beerService
    events:
      - http:
          path: isbeercold
          method: get